interval: 300
feeds:
  - id: usn
    feed_url: https://ubuntu.com/security/notices/rss.xml
    name: Ubuntu Security Notice
    gitlab_project_id: 2389
    retroactive: true
    added_since: "2022-04-14T00:00:00Z"
    labels:
      - Ubuntu

  - id: tomcat
    feed_url: https://tomcat.markmail.org/atom/+list:org.apache.tomcat.announce
    name: Tomcat Announcements
    gitlab_project_id: 2389
    retroactive: true
    added_since: "2022-04-14T00:00:00Z"
    labels:
      - Tomcat